### ISSUE TITLE
Android Studio 3 - NoClassDefFoundError

### ISSUE THREAD

**Issue by hDusan** [tonyofrancis/Fetch#100] opened 2018-01-07 10:22 UTC
Current date: 2018-01-07 11:15:12 
Device: Samsung SM-G935F
Android Studio 3.0.1

////////////////////////

NoClassDefFoundError after call fetch builder

new Fetch.Builder(context, string)
                        .setDownloadConcurrentLimit(4) // Allows Fetch to download 4 downloads in Parallel.
                        .enableLogging(true)
                        .build();

////////////////////////
                             
Stack trace:  
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
at com.tonyodev.fetch2.Fetch$Builder.<init>(Fetch.kt)
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.tonyodev.fetch2.Fetch$Builder.<init>(Fetch.kt)

Idea?

**Comment by sathiyarajcbe** [comment] 2018-01-07 16:41
No Class Definition Found! Our implementation/updation pending kindly do the needful ASAP
------------------------------------------------------------------------------------------------
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;                                                                                     at com.tonyodev.fetch2.Fetch$Builder.<init>(Fetch.kt)                                                                                     at com.example.myapplication_blank.App.getFetch(App.java:35)                                                                                     at com.example.myapplication_blank.SingleDownloadActivity.onCreate(SingleDownloadActivity.java:48)                                                                                     at android.app.Activity.performCreate(Activity.java:6662)

**Comment by tonyofrancis** [comment] 2018-01-07 17:08
@hDusan @sathiyarajcbe . I was able to replicate this issue. The Kotlin runtime and standard library apparently is not getting packed with Fetch version 2.0.0-RC2. mhm. I am working on this fix right now.

**Comment by tonyofrancis** [comment] 2018-01-08 00:02
@hDusan @sathiyarajcbe. The issue is now fixed in `com.tonyodev.fetch2:fetch2:2.0.0-RC3`. Please let me know if you find any other issues. Thanks.

-Tonyo

**Closed by tonyofrancis** 2018-01-08 00:02 UTC
Labels: bug

**Comment by sathiyarajcbe** [comment] 2018-01-08 14:16
There is any possibility for limiting/ to increase the download speed?

**Comment by sathiyarajcbe** [comment] 2018-01-09 04:52
NoClassDefFoundError while using RxFetch
_____________________________________________
rxFetch = new RxFetch.Builder(this, "GameFilesFetch")
                    .setLogger(logger)
                    .setDownloadConcurrentLimit(concurrentLimit)
                    .enableLogging(enableLogging)
                    .build();

  java.lang.NoClassDefFoundError: Failed resolution of: Lio/reactivex/android/schedulers/AndroidSchedulers;
 at com.tonyodev.fetch2rx.RxFetchImpl.<init>(RxFetchImpl.kt:25)
 at com.tonyodev.fetch2rx.RxFetchImpl$Companion.newInstance(RxFetchImpl.kt:184)
at com.tonyodev.fetch2rx.RxFetch$Builder.build(RxFetch.kt:140)
at com.tonyodev.fetch2rx.RxFetch$Builder.build(RxFetch.kt:119)

**Comment by sathiyarajcbe** [comment] 2018-01-09 04:54
Also downloading speed is very low when comparing v1.1.5. Even I have added the buffer size to 8192.
