### ISSUE TITLE
Cannot Resume group

### ISSUE THREAD

**Issue by Sergios21** [tonyofrancis/Fetch#128] opened 2018-04-16 14:35 UTC
Hello Tony,

I've faced a new issue. I'm incorporating some pause/resume logic in my downloader. I initialise my two downloader instances of Fetch and enqueue my lists of download requests (one at each downloader). Each enqueued request has the same group id. The pauseGroup() method works like a charm. When I try to resume the downloads by using the resumeGroup() method it only resumes very few downloads (1-4 and sometimes even none at all). When I run the getDownloadInGroup () I get all the initial downloads that I enqueued. Am I doing something wrong?

I've tried both with and without an OKHttp client and the results were the same. My concurrent limit is 10.

**Comment by tonyofrancis** [comment] 2018-04-16 15:02
@Sergios21 looking into this. I will update you soon

**Comment by tonyofrancis** [comment] 2018-04-16 16:34
@Sergios21. Fetch will only pause downloads that have the status of `Status.QUEUED or Status.DOWNLOADING`. So if you are using the `pauseGroup(groupId)` method, only downloads with status `Status.QUEUED or Status.DOWNLOADING` will be paused. The `onPaused(download)` method on attached Fetch Listeners will only be called for downloads that were actually paused. 

Fetch will only resume downloads that have a status of `Status.PAUSED`. The `onResume(download)` method on attached Fetch Listeners will only be called for these downloads when resumed. Meaning their statuses were changed to `Status.QUEUED`.

Question: What is the status of all the downloads in the group after calling `resumeGroup(groupId)` method?. Use the `getDownloadsInGroup(groupId, callback)` method and let me know the results. That way we can verify this issue.

**Comment by Sergios21** [comment] 2018-04-16 17:13
The files in the queue that have not been completed have a status of FAILED and the error is "FILE_NOT_FOUND". Following is a snapshot of a failed file.

created = 518679961846929
downloaded = 0
error = {Error@9266} "FILE_NOT_FOUND"
file = "/pathtofile/toolbarButton-pageUp%402x.png"
group = 2121210
headers = {LinkedHashMap@9268}  size = 0
id = -2109345191
namespace = "app_assets"
networkType = {NetworkType@9270} "ALL"
priority = {Priority@9271} "NORMAL"
status = {Status@9272} "FAILED"
tag = null
total = -1
url = "asset_url"

**Comment by tonyofrancis** [comment] 2018-04-16 17:26
@Sergios21 Can you test version 2.0.0-RC-12 and let me know if it works as expected for you. I have a feeling a bug was introduced in 2.0.0-RC13

**Comment by Sergios21** [comment] 2018-04-16 17:34
Yes, you are correct. On RC12 everything works as expected.

**Comment by tonyofrancis** [comment] 2018-04-16 17:35
@Sergios21 Great. I know what the issue is. Going to fix soon.

**Comment by tonyofrancis** [comment] 2018-04-17 00:42
This issue is now fixed in version 2.0.0-RC14

**Closed by tonyofrancis** 2018-04-17 00:42 UTC
Labels: bug
